export const DEFAULT_REDUCER_HELLO = 'DEFAULT_REDUCER_HELLO';
export const ADD_PRODUCT_TO_CART ='ADD_PRODUCT_TO_CART';
export const SUBTRACT_PRODUCT_NUMBER = 'SUBTRACT_PRODUCT_NUMBER';
export const PLUS_PRODUCT_NUMBER = 'PLUS_PRODUCT_NUMBER';
export const REMOVE_PRODUCT = 'REMOVE_PRODUCT';